name: Build & Upload to GitHub Releases

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release (e.g., v1.0.0)"
        required: true
      release_name:
        description: "Release name (optional)"
        required: false
        default: ""
      description:
        description: "What's new in this release (Release Notes)"
        required: true
      prerelease:
        description: "Is this a pre-release? (true/false)"
        required: false
        default: "false"

jobs:
  buildAndUpload:
    permissions:
      contents: write
    name: Build & Upload Release to GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android environment
        uses: android-actions/setup-android@v3

      - name: Build APK with Debug Keystore
        run: |
          chmod +x gradlew
          ./gradlew clean assembleRelease \
            -Pandroid.injected.signing.store.file=$HOME/.android/debug.keystore \
            -Pandroid.injected.signing.store.password=android \
            -Pandroid.injected.signing.key.alias=androiddebugkey \
            -Pandroid.injected.signing.key.password=android

      - name: Prepare Release Notes
        run: echo "${{ github.event.inputs.description }}" > release_notes.txt

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          body_path: release_notes.txt
          files: |
            app/build/outputs/apk/release/app-release.apk
          prerelease: ${{ github.event.inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
